#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CER smart-meter missing-value imputation training script.

Designed for datasets generated by create_cer_online_mask_dataset_fixed.py:

- train.csv: clean 7-day windows. Every clean window is expanded to all nine
  missing patterns in every epoch; exact masks and target days are regenerated
  online for every epoch.
- val.csv / test.csv: fixed masks, with nine configurations:
  random_10/20/40, block_3h/6h/12h, mixed_3h/6h/12h.

Model: simple three-branch gap-aware direct-prediction imputer
1) mask-aware multi-scale within-day convolution branch;
2) same-slot cross-day periodic-attention branch;
3) full-sequence bidirectional GRU branch;
4) a gap-feature-only per-position softmax gate that directly combines the
   three branch predictions. Same-slot observed means are periodic features,
   never a separate output path.

The model never receives pattern_id, missing_type, or missing_level as input.
Those labels are used only for grouped evaluation.
"""

from __future__ import annotations

import argparse
import gc
import json
import math
import os
import random
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

try:
    from tqdm import tqdm
except ImportError:  # pragma: no cover
    def tqdm(iterable=None, *args, **kwargs):
        return iterable if iterable is not None else range(int(kwargs.get("total", 0)))


SLOTS_PER_DAY = 48
DEFAULT_WINDOW_DAYS = 7
DEFAULT_SEQUENCE_LENGTH = SLOTS_PER_DAY * DEFAULT_WINDOW_DAYS
MODEL_NAME = "SimpleGapAwareThreeBranchImputer"


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
@dataclass(frozen=True)
class PatternSpec:
    pattern_id: str
    missing_type: str
    missing_level: str
    random_ratio: float = 0.0
    block_length: int = 0


DEFAULT_PATTERNS: Tuple[PatternSpec, ...] = (
    PatternSpec("random_10", "random", "10pct", random_ratio=0.10),
    PatternSpec("random_20", "random", "20pct", random_ratio=0.20),
    PatternSpec("random_40", "random", "40pct", random_ratio=0.40),
    PatternSpec("block_3h", "single_block", "3h", block_length=6),
    PatternSpec("block_6h", "single_block", "6h", block_length=12),
    PatternSpec("block_12h", "single_block", "12h", block_length=24),
    PatternSpec("mixed_3h", "mixed", "3h_plus_random", block_length=6),
    PatternSpec("mixed_6h", "mixed", "6h_plus_random", block_length=12),
    PatternSpec("mixed_12h", "mixed", "12h_plus_random", block_length=24),
)


@dataclass
class TrainConfig:
    data_dir: str = "datasets"
    out_dir: str = "runs/pbmrnet"
    epochs: int = 130
    batch_size: int = 64
    learning_rate: float = 7e-4
    weight_decay: float = 1e-4
    patience: int = 20
    scheduler_patience: int = 7
    scheduler_factor: float = 0.5
    min_delta: float = 1e-5
    local_dim: int = 80
    periodic_dim: int = 80
    global_dim: int = 160
    local_blocks: int = 2
    periodic_heads: int = 4
    gate_hidden_dim: int = 16
    gate_input: str = "gap_only"
    dropout: float = 0.10
    lambda_branch: float = 0.05
    huber_beta: float = 0.2
    grad_clip: float = 1.0
    num_workers: int = 0
    seed: int = 42
    amp: bool = True
    nonnegative_clip: bool = True
    skip_test: bool = False
    save_prediction_examples: int = 100
    ablation: str = "none"


def parse_args() -> TrainConfig:
    parser = argparse.ArgumentParser(
        description="CER gap-aware three-branch imputer training."
    )
    parser.add_argument("--data_dir", default="datasets")
    parser.add_argument("--out_dir", default="runs/pbmrnet")
    parser.add_argument("--epochs", type=int, default=130)
    parser.add_argument("--batch_size", type=int, default=64)
    parser.add_argument("--learning_rate", type=float, default=7e-4)
    parser.add_argument("--weight_decay", type=float, default=1e-4)
    parser.add_argument("--patience", type=int, default=20)
    parser.add_argument("--scheduler_patience", type=int, default=7)
    parser.add_argument("--scheduler_factor", type=float, default=0.5)
    parser.add_argument("--min_delta", type=float, default=1e-5)
    parser.add_argument("--local_dim", type=int, default=80)
    parser.add_argument("--periodic_dim", type=int, default=80)
    parser.add_argument("--global_dim", type=int, default=160)
    parser.add_argument("--local_blocks", type=int, choices=(1, 2), default=2)
    parser.add_argument("--periodic_heads", type=int, default=4)
    parser.add_argument("--gate_hidden_dim", type=int, default=16)
    parser.add_argument("--gate_input", choices=("gap_only", "gap_plus_time"), default="gap_only")
    parser.add_argument("--dropout", type=float, default=0.10)
    parser.add_argument("--lambda_branch", type=float, default=0.05)
    parser.add_argument("--huber_beta", type=float, default=0.2)
    parser.add_argument("--grad_clip", type=float, default=1.0)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--no_amp", action="store_true")
    parser.add_argument("--no_nonnegative_clip", action="store_true")
    test_group = parser.add_mutually_exclusive_group()
    test_group.add_argument("--skip_test", action="store_true", help="Skip the final test evaluation.")
    test_group.add_argument("--run_test", action="store_true", help="Run the final test evaluation (already the default).")
    parser.add_argument("--save_prediction_examples", type=int, default=100)
    ablations = parser.add_mutually_exclusive_group()
    for name in ("no_local", "no_periodic", "no_global", "average_gate", "no_gap", "no_periodic_base", "no_auxiliary_loss"):
        ablations.add_argument(f"--ablate_{name}", action="store_true")
    args = parser.parse_args()

    cfg = TrainConfig(
        data_dir=args.data_dir,
        out_dir=args.out_dir,
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        weight_decay=args.weight_decay,
        patience=args.patience,
        scheduler_patience=args.scheduler_patience,
        scheduler_factor=args.scheduler_factor,
        min_delta=args.min_delta,
        local_dim=args.local_dim,
        periodic_dim=args.periodic_dim,
        global_dim=args.global_dim,
        local_blocks=args.local_blocks,
        periodic_heads=args.periodic_heads,
        gate_hidden_dim=args.gate_hidden_dim,
        gate_input=args.gate_input,
        dropout=args.dropout,
        lambda_branch=args.lambda_branch,
        huber_beta=args.huber_beta,
        grad_clip=args.grad_clip,
        num_workers=args.num_workers,
        seed=args.seed,
        amp=not args.no_amp,
        nonnegative_clip=not args.no_nonnegative_clip,
        skip_test=args.skip_test,
        save_prediction_examples=args.save_prediction_examples,
        ablation=next((name for name in ("no_local", "no_periodic", "no_global", "average_gate", "no_gap", "no_periodic_base", "no_auxiliary_loss") if getattr(args, f"ablate_{name}")), "none"),
    )
    validate_train_config(cfg)
    return cfg


def validate_train_config(cfg: TrainConfig) -> None:
    if cfg.epochs <= 0 or cfg.batch_size <= 0:
        raise ValueError("epochs and batch_size must be positive")
    if cfg.learning_rate <= 0:
        raise ValueError("learning_rate must be positive")
    if min(cfg.local_dim, cfg.periodic_dim, cfg.global_dim) <= 0:
        raise ValueError("branch dimensions must be positive")
    if cfg.global_dim % 2 != 0:
        raise ValueError("global_dim must be even for the bidirectional GRU")
    if cfg.periodic_heads <= 0 or cfg.periodic_dim % cfg.periodic_heads != 0:
        raise ValueError("periodic_dim must be divisible by periodic_heads")
    if cfg.gate_hidden_dim <= 0:
        raise ValueError("gate_hidden_dim must be positive")
    if not (0.0 <= cfg.dropout < 1.0):
        raise ValueError("dropout must be in [0, 1)")
    if cfg.lambda_branch < 0:
        raise ValueError("lambda_branch cannot be negative")
    if cfg.huber_beta <= 0:
        raise ValueError("huber_beta must be positive")


# -----------------------------------------------------------------------------
# Reproducibility and utilities
# -----------------------------------------------------------------------------
def seed_everything(seed: int) -> None:
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    # Deterministic mode is intentionally not forced because it can substantially
    # slow GRU and attention kernels. Fixed seeds still make runs highly repeatable.


def seed_worker(worker_id: int) -> None:
    worker_seed = torch.initial_seed() % (2**32)
    np.random.seed(worker_seed)
    random.seed(worker_seed)


def load_patterns(data_dir: Path) -> Tuple[Tuple[PatternSpec, ...], float]:
    # The adapted dataset directory intentionally contains CSV files only.
    # Keep the nine protocol-defined patterns fixed inside this script.
    del data_dir
    return DEFAULT_PATTERNS, 0.10


def _ordered_columns(header: Sequence[str], prefix: str) -> List[str]:
    columns = sorted(
        (c for c in header if c.startswith(prefix)),
        key=lambda name: int(name[len(prefix):]),
    )
    expected = [f"{prefix}{index:03d}" for index in range(DEFAULT_SEQUENCE_LENGTH)]
    if columns != expected:
        raise RuntimeError(
            f"Expected exactly {DEFAULT_SEQUENCE_LENGTH} columns {prefix}000..{prefix}335; "
            f"found {len(columns)}"
        )
    return columns


def discover_clean_columns(csv_path: Path) -> List[str]:
    header = pd.read_csv(csv_path, nrows=0).columns.tolist()
    return _ordered_columns(header, "load_")


def discover_sequence_columns(csv_path: Path) -> Tuple[List[str], List[str], List[str]]:
    header = pd.read_csv(csv_path, nrows=0).columns.tolist()
    x_cols = _ordered_columns(header, "x_")
    mask_cols = _ordered_columns(header, "mask_")
    y_cols = _ordered_columns(header, "y_")
    return x_cols, mask_cols, y_cols


def make_pattern_maps(patterns: Sequence[PatternSpec]) -> Tuple[Dict[str, int], Dict[int, str]]:
    to_index = {p.pattern_id: i for i, p in enumerate(patterns)}
    to_name = {i: p.pattern_id for i, p in enumerate(patterns)}
    return to_index, to_name


# -----------------------------------------------------------------------------
# Dataset and online masking
# -----------------------------------------------------------------------------
def build_online_mask(
    pattern: PatternSpec,
    target_day: int,
    window_days: int,
    mixed_random_ratio: float,
    rng: np.random.Generator,
) -> np.ndarray:
    sequence_length = window_days * SLOTS_PER_DAY
    mask = np.ones(sequence_length, dtype=np.uint8)
    day_offset = target_day * SLOTS_PER_DAY

    if pattern.missing_type == "random":
        count = max(1, int(round(SLOTS_PER_DAY * pattern.random_ratio)))
        local_idx = rng.choice(SLOTS_PER_DAY, size=count, replace=False)
        mask[day_offset + local_idx] = 0

    elif pattern.missing_type == "single_block":
        length = int(pattern.block_length)
        start = int(rng.integers(0, SLOTS_PER_DAY - length + 1))
        mask[day_offset + start : day_offset + start + length] = 0

    elif pattern.missing_type == "mixed":
        length = int(pattern.block_length)
        start = int(rng.integers(0, SLOTS_PER_DAY - length + 1))
        block_local = np.arange(start, start + length)
        mask[day_offset + block_local] = 0

        remaining = np.setdiff1d(np.arange(SLOTS_PER_DAY), block_local, assume_unique=True)
        count = max(1, int(round(len(remaining) * mixed_random_ratio)))
        count = min(count, len(remaining))
        random_local = rng.choice(remaining, size=count, replace=False)
        mask[day_offset + random_local] = 0
    else:
        raise ValueError(f"Unknown missing_type: {pattern.missing_type}")

    return mask


class OnlineMaskTrainDataset(Dataset):
    """
    Loads clean 7-day windows and exposes all nine missing patterns for every
    clean window in every epoch.

    If train.csv contains N clean windows and there are P patterns, then:

        len(dataset) = N * P

    Pattern coverage is deterministic within each epoch (every clean window sees
    every pattern exactly once), while the target day and exact missing positions
    are regenerated online from a seed that depends on epoch, clean-window index,
    and pattern index. Thus the protocol is reproducible but still changes masks
    across epochs.
    """

    def __init__(
        self,
        csv_path: Path,
        patterns: Sequence[PatternSpec],
        mixed_random_ratio: float,
        seed: int,
    ) -> None:
        self.csv_path = csv_path
        self.patterns = tuple(patterns)
        self.mixed_random_ratio = float(mixed_random_ratio)
        self.seed = int(seed)
        self.epoch = 0

        load_cols = discover_clean_columns(csv_path)
        meta_cols = ["sample_id", "meter_id"]
        frame = pd.read_csv(
            csv_path,
            usecols=meta_cols + load_cols,
            dtype={**{c: np.float32 for c in load_cols}, "sample_id": str, "meter_id": str},
            low_memory=False,
        )
        self.y = frame[load_cols].to_numpy(dtype=np.float32, copy=True)
        self.sample_ids = frame["sample_id"].astype(str).to_numpy()
        self.clean_ids = self.sample_ids.copy()
        self.meter_ids = frame["meter_id"].astype(str).to_numpy()
        del frame

        self.num_clean_windows = len(self.y)
        self.num_patterns = len(self.patterns)
        self.sequence_length = self.y.shape[1]
        if self.sequence_length % SLOTS_PER_DAY != 0:
            raise RuntimeError("Sequence length must be divisible by 48")
        self.window_days = self.sequence_length // SLOTS_PER_DAY

        print(f"Clean training windows: {self.num_clean_windows:,}")
        print(f"Patterns per clean window: {self.num_patterns}")
        print(f"Effective training samples per epoch: {len(self):,}")

    def set_epoch(self, epoch: int) -> None:
        self.epoch = int(epoch)

    def __len__(self) -> int:
        return self.num_clean_windows * self.num_patterns

    def __getitem__(self, index: int) -> Dict[str, object]:
        # Layout:
        #   0..P-1       -> clean window 0, all P patterns
        #   P..2P-1      -> clean window 1, all P patterns
        #   ...
        clean_index = int(index) // self.num_patterns
        pattern_index = int(index) % self.num_patterns
        pattern = self.patterns[pattern_index]

        # Reproducible within an epoch, but dynamic across epochs.
        seq = np.random.SeedSequence(
            [self.seed, self.epoch, clean_index, pattern_index]
        )
        rng = np.random.default_rng(seq)
        target_day = int(rng.integers(0, self.window_days))

        mask = build_online_mask(
            pattern,
            target_day,
            self.window_days,
            self.mixed_random_ratio,
            rng,
        )
        y = self.y[clean_index]
        x = y.copy()
        x[mask == 0] = 0.0

        expanded_sample_id = (
            f"{self.sample_ids[clean_index]}__{pattern.pattern_id}"
        )

        return {
            "x": torch.from_numpy(x),
            "mask": torch.from_numpy(mask.astype(np.float32)),
            "y": torch.from_numpy(y),
            "pattern_index": pattern_index,
            "target_day": target_day,
            "sample_id": expanded_sample_id,
            "clean_id": self.clean_ids[clean_index],
            "meter_id": self.meter_ids[clean_index],
        }


class FixedMaskDataset(Dataset):
    def __init__(
        self,
        csv_path: Path,
        pattern_to_index: Mapping[str, int],
    ) -> None:
        self.csv_path = csv_path
        x_cols, mask_cols, y_cols = discover_sequence_columns(csv_path)
        meta_cols = [
            "sample_id",
            "clean_id",
            "meter_id",
            "pattern_id",
            "missing_type",
            "missing_level",
            "target_day_index",
        ]
        dtype: Dict[str, object] = {c: np.float32 for c in x_cols + y_cols}
        dtype.update({c: np.uint8 for c in mask_cols})
        dtype.update(
            {
                "sample_id": str,
                "clean_id": str,
                "meter_id": str,
                "pattern_id": str,
                "missing_type": str,
                "missing_level": str,
                "target_day_index": np.int16,
            }
        )
        frame = pd.read_csv(
            csv_path,
            usecols=meta_cols + x_cols + mask_cols + y_cols,
            dtype=dtype,
            low_memory=False,
        )
        self.x = frame[x_cols].to_numpy(dtype=np.float32, copy=True)
        self.mask = frame[mask_cols].to_numpy(dtype=np.float32, copy=True)
        self.y = frame[y_cols].to_numpy(dtype=np.float32, copy=True)
        self.sample_ids = frame["sample_id"].astype(str).to_numpy()
        self.clean_ids = frame["clean_id"].astype(str).to_numpy()
        self.meter_ids = frame["meter_id"].astype(str).to_numpy()
        self.pattern_ids = frame["pattern_id"].astype(str).to_numpy()
        self.missing_types = frame["missing_type"].astype(str).to_numpy()
        self.missing_levels = frame["missing_level"].astype(str).to_numpy()
        self.target_days = frame["target_day_index"].to_numpy(dtype=np.int64, copy=True)
        try:
            self.pattern_indices = np.asarray(
                [pattern_to_index[p] for p in self.pattern_ids], dtype=np.int64
            )
        except KeyError as exc:
            raise RuntimeError(f"Unknown pattern_id in {csv_path}: {exc}") from exc
        del frame

        if self.x.shape[1] != DEFAULT_SEQUENCE_LENGTH:
            raise RuntimeError(f"Expected 336 sequence points in {csv_path}")
        if not np.isin(self.mask, (0.0, 1.0)).all():
            raise RuntimeError(f"Mask must contain only 0/1 in {csv_path}")
        if np.any(self.mask.sum(axis=1) >= self.mask.shape[1]):
            raise RuntimeError(f"Every fixed-mask sample must contain a missing point in {csv_path}")

    def __len__(self) -> int:
        return len(self.x)

    def __getitem__(self, index: int) -> Dict[str, object]:
        return {
            "x": torch.from_numpy(self.x[index]),
            "mask": torch.from_numpy(self.mask[index]),
            "y": torch.from_numpy(self.y[index]),
            "pattern_index": int(self.pattern_indices[index]),
            "target_day": int(self.target_days[index]),
            "sample_id": self.sample_ids[index],
            "clean_id": self.clean_ids[index],
            "meter_id": self.meter_ids[index],
        }


def audit_datasets(
    train_path: Path,
    val_path: Path,
    test_path: Optional[Path],
    patterns: Sequence[PatternSpec],
) -> Dict[str, object]:
    """Validate real CSV schemas, values, patterns, groups, and meter isolation."""
    expected_patterns = {pattern.pattern_id for pattern in patterns}
    report: Dict[str, object] = {}

    load_cols = discover_clean_columns(train_path)
    train_frame = pd.read_csv(
        train_path,
        usecols=["sample_id", "meter_id"] + load_cols,
        dtype={**{column: np.float32 for column in load_cols}, "sample_id": str, "meter_id": str},
        low_memory=False,
    )
    train_values = train_frame[load_cols].to_numpy(dtype=np.float32, copy=False)
    if np.isnan(train_values).any() or np.isinf(train_values).any():
        raise RuntimeError("train.csv contains NaN or Inf in load columns")
    if (train_values < 0).any():
        raise RuntimeError("train.csv contains negative load values")
    train_meters = set(train_frame["meter_id"].astype(str))
    report["train"] = {
        "shape": [len(train_frame), len(pd.read_csv(train_path, nrows=0).columns)],
        "rows": len(train_frame),
        "meter_count": len(train_meters),
        "load_columns": len(load_cols),
        "nan_count": int(np.isnan(train_values).sum()),
        "inf_count": int(np.isinf(train_values).sum()),
        "negative_count": int((train_values < 0).sum()),
    }
    del train_values

    split_meters: Dict[str, set] = {"train": train_meters}
    fixed_splits = [("val", val_path)]
    if test_path is not None:
        fixed_splits.append(("test", test_path))
    for split, path in fixed_splits:
        x_cols, mask_cols, y_cols = discover_sequence_columns(path)
        meta_cols = [
            "sample_id", "clean_id", "meter_id", "pattern_id",
            "missing_type", "missing_level", "target_day_index",
        ]
        dtype: Dict[str, object] = {column: np.float32 for column in x_cols + y_cols}
        dtype.update({column: np.uint8 for column in mask_cols})
        dtype.update({column: str for column in meta_cols[:-1]})
        dtype["target_day_index"] = np.int16
        frame = pd.read_csv(path, usecols=meta_cols + x_cols + mask_cols + y_cols,
                            dtype=dtype, low_memory=False)
        x = frame[x_cols].to_numpy(dtype=np.float32, copy=False)
        mask = frame[mask_cols].to_numpy(dtype=np.uint8, copy=False)
        y = frame[y_cols].to_numpy(dtype=np.float32, copy=False)
        actual_patterns = set(frame["pattern_id"].astype(str))
        if actual_patterns != expected_patterns:
            raise RuntimeError(
                f"{split}.csv pattern mismatch: missing={sorted(expected_patterns-actual_patterns)}, "
                f"unknown={sorted(actual_patterns-expected_patterns)}"
            )
        if np.isnan(x).any() or np.isnan(y).any() or np.isinf(x).any() or np.isinf(y).any():
            raise RuntimeError(f"{split}.csv contains NaN or Inf in x/y columns")
        if not np.isin(mask, (0, 1)).all():
            raise RuntimeError(f"{split}.csv mask contains values other than 0/1")
        missing_per_row = (mask == 0).sum(axis=1)
        if np.any(missing_per_row < 1):
            raise RuntimeError(f"{split}.csv contains a sample without missing points")
        group_sizes = frame.groupby("clean_id")["pattern_id"].nunique()
        if not (group_sizes == len(patterns)).all():
            raise RuntimeError(f"Each clean_id in {split}.csv must map to all nine patterns")
        meters = set(frame["meter_id"].astype(str))
        split_meters[split] = meters
        report[split] = {
            "shape": [len(frame), len(pd.read_csv(path, nrows=0).columns)],
            "rows": len(frame),
            "meter_count": len(meters),
            "clean_id_count": int(frame["clean_id"].nunique()),
            "pattern_count": len(actual_patterns),
            "sequence_columns": {"x": len(x_cols), "mask": len(mask_cols), "y": len(y_cols)},
            "mask_values": sorted(int(value) for value in np.unique(mask)),
            "minimum_missing_points": int(missing_per_row.min()),
        }
        del x, mask, y, frame

    overlap_train_val = split_meters["train"] & split_meters["val"]
    overlap_train_test = split_meters["train"] & split_meters.get("test", set())
    overlap_val_test = split_meters["val"] & split_meters.get("test", set())
    if overlap_train_val or overlap_train_test or overlap_val_test:
        raise RuntimeError(
            "Meter leakage detected: "
            f"train/val={len(overlap_train_val)}, train/test={len(overlap_train_test)}, "
            f"val/test={len(overlap_val_test)}"
        )
    report["meter_overlap"] = {"train_val": 0}
    if test_path is not None:
        report["meter_overlap"].update({"train_test": 0, "val_test": 0})
    print("\nDataset audit:")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    print("Meter split leakage check: PASS")
    return report


def check_mask_protocols(
    train_dataset: OnlineMaskTrainDataset,
    val_dataset: FixedMaskDataset,
    test_dataset: Optional[FixedMaskDataset],
) -> None:
    # Every clean window must expose all nine patterns once per epoch.
    train_dataset.set_epoch(1)
    first_window_pattern_indices = [
        int(train_dataset[i]["pattern_index"])
        for i in range(train_dataset.num_patterns)
    ]
    expected_pattern_indices = list(range(train_dataset.num_patterns))
    if first_window_pattern_indices != expected_pattern_indices:
        raise RuntimeError("Nine-pattern training coverage check failed")
    print("Nine-pattern training coverage check: PASS")

    # Same epoch/sample must be reproducible; different epochs should regenerate
    # the exact mask for the same clean-window/pattern pair.
    train_dataset.set_epoch(1)
    epoch1 = train_dataset[0]["mask"].clone()
    train_dataset.set_epoch(2)
    epoch2 = train_dataset[0]["mask"].clone()
    train_dataset.set_epoch(1)
    epoch1_repeat = train_dataset[0]["mask"].clone()

    if not torch.equal(epoch1, epoch1_repeat):
        raise RuntimeError("Online mask reproducibility check failed")
    if torch.equal(epoch1, epoch2):
        # Extremely rare collisions are possible for a discrete mask generator.
        # Verify a few additional pattern/window pairs before declaring failure.
        changed = False
        probe_count = min(32, len(train_dataset))
        for probe in range(1, probe_count):
            train_dataset.set_epoch(1)
            mask_a = train_dataset[probe]["mask"]
            train_dataset.set_epoch(2)
            mask_b = train_dataset[probe]["mask"]
            if not torch.equal(mask_a, mask_b):
                changed = True
                break
        if not changed:
            raise RuntimeError("Online masks did not change across epochs")
    train_dataset.set_epoch(1)
    print("Online mask reproducibility/dynamic-change check: PASS")

    first_val = val_dataset[0]
    second_val = val_dataset[0]
    if not all(torch.equal(first_val[key], second_val[key]) for key in ("x", "mask", "y")):
        raise RuntimeError("Validation fixed-mask check failed")
    print("Validation fixed-mask check: PASS")

    if test_dataset is not None:
        first_test = test_dataset[0]
        second_test = test_dataset[0]
        if not all(torch.equal(first_test[key], second_test[key]) for key in ("x", "mask", "y")):
            raise RuntimeError("Test fixed-mask check failed")
        print("Test fixed-mask check: PASS")


# -----------------------------------------------------------------------------
# Model
# -----------------------------------------------------------------------------
class ChannelLayerNorm(nn.Module):
    """LayerNorm for tensors shaped [B, C, T]."""

    def __init__(self, channels: int) -> None:
        super().__init__()
        self.norm = nn.LayerNorm(channels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.norm(x.transpose(1, 2)).transpose(1, 2)


class TemporalResidualBlock(nn.Module):
    def __init__(self, d_model: int, dropout: float) -> None:
        super().__init__()
        self.depthwise = nn.Conv1d(d_model, d_model, kernel_size=3, padding=1, groups=d_model)
        self.pointwise1 = nn.Conv1d(d_model, 2 * d_model, kernel_size=1)
        self.pointwise2 = nn.Conv1d(2 * d_model, d_model, kernel_size=1)
        self.norm = ChannelLayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        residual = x
        x = self.depthwise(x)
        x = F.gelu(self.pointwise1(x))
        x = self.dropout(self.pointwise2(x))
        return self.norm(residual + x)


class MaskAwareLocalBranch(nn.Module):
    """Within-day multi-scale mask-normalized temporal convolution."""

    def __init__(self, d_model: int, dropout: float, blocks: int = 2) -> None:
        super().__init__()
        self.kernels = (3, 5, 7)
        self.scale_convs = nn.ModuleList(
            [nn.Conv1d(1, 1, kernel_size=k, padding=k // 2, bias=False) for k in self.kernels]
        )
        self.input_proj = nn.Conv1d(7, d_model, kernel_size=1)
        self.blocks = nn.ModuleList([TemporalResidualBlock(d_model, dropout) for _ in range(blocks)])

    def forward(
        self,
        x_norm: torch.Tensor,
        mask: torch.Tensor,
        slot_sin: torch.Tensor,
        slot_cos: torch.Tensor,
        window_days: int,
    ) -> torch.Tensor:
        batch, length = x_norm.shape
        x_day = x_norm.view(batch * window_days, 1, SLOTS_PER_DAY)
        m_day = mask.view(batch * window_days, 1, SLOTS_PER_DAY)
        sin_day = slot_sin.view(1, 1, SLOTS_PER_DAY).expand(batch * window_days, -1, -1)
        cos_day = slot_cos.view(1, 1, SLOTS_PER_DAY).expand(batch * window_days, -1, -1)

        scales: List[torch.Tensor] = []
        for conv, kernel_size in zip(self.scale_convs, self.kernels):
            numerator = conv(x_day * m_day)
            kernel = torch.ones(
                1, 1, kernel_size, device=x_day.device, dtype=x_day.dtype
            )
            valid_count = F.conv1d(m_day, kernel, padding=kernel_size // 2)
            normalized = numerator * (float(kernel_size) / valid_count.clamp_min(1.0))
            normalized = torch.where(valid_count > 0, normalized, torch.zeros_like(normalized))
            scales.append(normalized)

        features = torch.cat([x_day, m_day, sin_day, cos_day] + scales, dim=1)
        hidden = F.gelu(self.input_proj(features))
        for block in self.blocks:
            hidden = block(hidden)
        hidden = hidden.transpose(1, 2).reshape(batch, length, -1)
        return hidden


class PeriodicAttentionBranch(nn.Module):
    """Attention only across days for the same half-hour slot."""

    def __init__(self, d_model: int, num_heads: int, dropout: float) -> None:
        super().__init__()
        self.input_proj = nn.Linear(6, d_model)
        self.attn = nn.MultiheadAttention(
            embed_dim=d_model,
            num_heads=num_heads,
            dropout=dropout,
            batch_first=True,
        )
        self.norm1 = nn.LayerNorm(d_model)
        self.ffn = nn.Sequential(
            nn.Linear(d_model, 2 * d_model),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(2 * d_model, d_model),
            nn.Dropout(dropout),
        )
        self.norm2 = nn.LayerNorm(d_model)

    def forward(
        self,
        x_norm: torch.Tensor,
        mask: torch.Tensor,
        time_features: torch.Tensor,
        window_days: int,
    ) -> torch.Tensor:
        batch = x_norm.shape[0]
        x_grid = x_norm.view(batch, window_days, SLOTS_PER_DAY)
        m_grid = mask.view(batch, window_days, SLOTS_PER_DAY)
        t_grid = time_features.view(batch, window_days, SLOTS_PER_DAY, 4)
        features = torch.cat([x_grid.unsqueeze(-1), m_grid.unsqueeze(-1), t_grid], dim=-1)

        # [B, D, S, F] -> [B*S, D, F]
        tokens = features.permute(0, 2, 1, 3).reshape(batch * SLOTS_PER_DAY, window_days, 6)
        tokens = self.input_proj(tokens)
        key_padding_mask = (
            m_grid.permute(0, 2, 1).reshape(batch * SLOTS_PER_DAY, window_days) < 0.5
        )

        # Defensive handling for unseen masks where all seven same-slot values are missing.
        all_missing = key_padding_mask.all(dim=1)
        if torch.any(all_missing):
            key_padding_mask = key_padding_mask.clone()
            tokens = tokens.clone()
            key_padding_mask[all_missing, 0] = False
            tokens[all_missing, 0] = 0.0

        attended, _ = self.attn(
            tokens,
            tokens,
            tokens,
            key_padding_mask=key_padding_mask,
            need_weights=False,
        )
        hidden = self.norm1(tokens + attended)
        hidden = self.norm2(hidden + self.ffn(hidden))
        hidden = hidden.view(batch, SLOTS_PER_DAY, window_days, -1)
        hidden = hidden.permute(0, 2, 1, 3).reshape(batch, window_days * SLOTS_PER_DAY, -1)
        return hidden


class GlobalBiGRUBranch(nn.Module):
    def __init__(self, d_model: int, dropout: float) -> None:
        super().__init__()
        self.input_proj = nn.Linear(6, d_model)
        self.gru = nn.GRU(
            input_size=d_model,
            hidden_size=d_model // 2,
            num_layers=1,
            batch_first=True,
            bidirectional=True,
        )
        self.norm = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(
        self,
        x_norm: torch.Tensor,
        mask: torch.Tensor,
        time_features: torch.Tensor,
    ) -> torch.Tensor:
        features = torch.cat([x_norm.unsqueeze(-1), mask.unsqueeze(-1), time_features], dim=-1)
        embedded = F.gelu(self.input_proj(features))
        hidden, _ = self.gru(embedded)
        return self.norm(embedded + self.dropout(hidden))


def compute_gap_features(mask: torch.Tensor, window_days: int) -> torch.Tensor:
    """Returns [missing, normalized gap length, local ratio, periodic ratio]."""
    batch = mask.shape[0]
    m = mask.view(batch * window_days, SLOTS_PER_DAY)
    missing = 1.0 - m

    forward = torch.zeros_like(m)
    run = torch.zeros(batch * window_days, device=m.device, dtype=m.dtype)
    for slot in range(SLOTS_PER_DAY):
        run = (run + 1.0) * missing[:, slot]
        forward[:, slot] = run

    backward = torch.zeros_like(m)
    run.zero_()
    for slot in range(SLOTS_PER_DAY - 1, -1, -1):
        run = (run + 1.0) * missing[:, slot]
        backward[:, slot] = run

    gap_length = (forward + backward - 1.0).clamp_min(0.0) * missing
    gap_length = gap_length / float(SLOTS_PER_DAY)
    local_ratio = F.avg_pool1d(
        m.unsqueeze(1), kernel_size=7, stride=1, padding=3
    ).squeeze(1)

    m_grid = mask.view(batch, window_days, SLOTS_PER_DAY)
    periodic_ratio = m_grid.mean(dim=1, keepdim=True).expand(-1, window_days, -1)

    output = torch.stack(
        [
            missing,
            gap_length,
            local_ratio,
            periodic_ratio.reshape(batch * window_days, SLOTS_PER_DAY),
        ],
        dim=-1,
    )
    return output.reshape(batch, window_days * SLOTS_PER_DAY, 4)



class SimpleGapAwareThreeBranchImputer(nn.Module):
    """Observed periodic base plus three residuals fused by a gap-aware gate."""
    def __init__(self, sequence_length: int, local_dim: int = 80,
                 periodic_dim: int = 80, global_dim: int = 160,
                 local_blocks: int = 2, periodic_heads: int = 4,
                 gate_hidden_dim: int = 16, gate_input: str = "gap_only",
                 dropout: float = 0.1, ablation: str = "none") -> None:
        super().__init__()
        if sequence_length % SLOTS_PER_DAY != 0:
            raise ValueError("sequence_length must be divisible by SLOTS_PER_DAY")
        self.sequence_length = int(sequence_length)
        self.window_days = sequence_length // SLOTS_PER_DAY
        self.local_dim = local_dim
        self.periodic_dim = periodic_dim
        self.global_dim = global_dim
        self.local_blocks = local_blocks
        self.periodic_heads = periodic_heads
        self.gate_hidden_dim = gate_hidden_dim
        self.gate_input = gate_input
        self.ablation = ablation
        self.periodic_heads = periodic_heads

        self.local_branch = MaskAwareLocalBranch(self.local_dim, dropout, local_blocks)
        self.periodic_branch = PeriodicAttentionBranch(self.periodic_dim, periodic_heads, dropout)
        self.global_branch = GlobalBiGRUBranch(self.global_dim, dropout)
        self.local_head = nn.Linear(self.local_dim, 1)
        self.periodic_head = nn.Linear(self.periodic_dim, 1)
        self.global_head = nn.Linear(self.global_dim, 1)
        gate_input_dim = 4 if gate_input == "gap_only" else 8
        self.gate = nn.Sequential(
            nn.Linear(gate_input_dim, gate_hidden_dim), nn.GELU(), nn.Dropout(dropout),
            nn.Linear(gate_hidden_dim, 3)
        )
        nn.init.zeros_(self.gate[-1].bias)

        day_index = torch.arange(self.window_days, dtype=torch.float32).repeat_interleave(SLOTS_PER_DAY)
        slot_index = torch.arange(SLOTS_PER_DAY, dtype=torch.float32).repeat(self.window_days)
        time_features = torch.stack([
            torch.sin(2 * math.pi * slot_index / SLOTS_PER_DAY),
            torch.cos(2 * math.pi * slot_index / SLOTS_PER_DAY),
            torch.sin(2 * math.pi * day_index / max(self.window_days, 1)),
            torch.cos(2 * math.pi * day_index / max(self.window_days, 1)),
        ], dim=-1)
        self.register_buffer("time_features", time_features, persistent=False)
        trainable = sum(p.numel() for p in self.parameters() if p.requires_grad)
        if trainable > 500_000:
            raise RuntimeError(f"Parameter limit exceeded: {trainable} > 500000")
        disabled = {
            "no_local": (self.local_branch, self.local_head),
            "no_periodic": (self.periodic_branch, self.periodic_head),
            "no_global": (self.global_branch, self.global_head),
        }.get(ablation, ())
        for module in disabled:
            for parameter in module.parameters():
                parameter.requires_grad_(False)


    @staticmethod
    def observed_normalize(x: torch.Tensor, mask: torch.Tensor):
        count = mask.sum(dim=1, keepdim=True).clamp_min(1.0)
        mean = (x * mask).sum(dim=1, keepdim=True) / count
        variance = (((x - mean) ** 2) * mask).sum(dim=1, keepdim=True) / count
        std = variance.sqrt().clamp_min(1e-3)
        return ((x - mean) / std) * mask, mean, std

    def periodic_base(self, x_norm: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        batch = x_norm.shape[0]
        x_grid = x_norm.view(batch, self.window_days, SLOTS_PER_DAY)
        m_grid = mask.view(batch, self.window_days, SLOTS_PER_DAY)
        slot_count = m_grid.sum(dim=1, keepdim=True)
        slot_mean = (x_grid * m_grid).sum(dim=1, keepdim=True) / slot_count.clamp_min(1.0)
        day_count = m_grid.sum(dim=2, keepdim=True)
        day_mean = (x_grid * m_grid).sum(dim=2, keepdim=True) / day_count.clamp_min(1.0)
        sample_count = mask.sum(dim=1, keepdim=True)
        sample_mean = (x_norm * mask).sum(dim=1, keepdim=True) / sample_count.clamp_min(1.0)
        fallback = torch.where(
            day_count > 0,
            day_mean.expand_as(x_grid),
            torch.where(
                sample_count.view(batch, 1, 1) > 0,
                sample_mean.view(batch, 1, 1).expand_as(x_grid),
                torch.zeros_like(x_grid),
            ),
        )
        base = torch.where(
            slot_count.expand_as(x_grid) > 0,
            slot_mean.expand_as(x_grid),
            fallback,
        )
        return base.reshape(batch, -1)

    def forward(self, x: torch.Tensor, mask: torch.Tensor) -> Dict[str, torch.Tensor]:
        x_norm, mean, std = self.observed_normalize(x, mask)
        tf = self.time_features.unsqueeze(0).expand(x.shape[0], -1, -1)
        local = self.local_branch(
            x_norm, mask,
            self.time_features[:SLOTS_PER_DAY, 0],
            self.time_features[:SLOTS_PER_DAY, 1],
            self.window_days,
        )
        periodic = self.periodic_branch(x_norm, mask, tf, self.window_days)
        global_feature = self.global_branch(x_norm, mask, tf)
        gap = compute_gap_features(mask, self.window_days)
        local_residual = self.local_head(local).squeeze(-1)
        periodic_residual = self.periodic_head(periodic).squeeze(-1)
        global_residual = self.global_head(global_feature).squeeze(-1)
        branch_residual = torch.stack([local_residual, periodic_residual, global_residual], dim=-1)
        gate_features = gap if self.gate_input == "gap_only" else torch.cat([gap, tf], dim=-1)
        if self.ablation == "no_gap":
            gate_features = torch.zeros_like(gate_features)
        valid = torch.ones(3, device=x.device, dtype=x.dtype)
        if self.ablation == "no_local": valid[0] = 0.0
        if self.ablation == "no_periodic": valid[1] = 0.0
        if self.ablation == "no_global": valid[2] = 0.0
        if self.ablation == "average_gate":
            gate_weights = valid.view(1, 1, 3).expand(x.shape[0], x.shape[1], -1)
        else:
            gate_weights = torch.softmax(self.gate(gate_features), dim=-1) * valid.view(1, 1, 3)
        gate_weights = gate_weights / gate_weights.sum(dim=-1, keepdim=True).clamp_min(1e-8)
        periodic_base = self.periodic_base(x_norm, mask)
        if self.ablation == "no_periodic_base":
            periodic_base = torch.zeros_like(periodic_base)
        branch_prediction_norm = periodic_base.unsqueeze(-1) + branch_residual
        gated_residual = (gate_weights * branch_residual).sum(dim=-1)
        prediction_norm = periodic_base + gated_residual
        return {"prediction_norm": prediction_norm, "branch_prediction_norm": branch_prediction_norm,
                "gate_weights": gate_weights, "mean": mean, "std": std,
                "gap_features": gap,
                "periodic_base": periodic_base,
                "local_residual": local_residual,
                "periodic_residual": periodic_residual,
                "global_residual": global_residual}


# -----------------------------------------------------------------------------
# Loss and metrics
# -----------------------------------------------------------------------------
def missing_huber_loss(
    prediction: torch.Tensor,
    target: torch.Tensor,
    mask: torch.Tensor,
    beta: float,
) -> torch.Tensor:
    missing = 1.0 - mask
    point_loss = F.smooth_l1_loss(
        prediction, target, reduction="none", beta=beta
    )
    return (point_loss * missing).sum() / missing.sum().clamp_min(1.0)


def parameter_breakdown(model: nn.Module) -> Dict[str, int]:
    groups = {
        "local_branch": ("local_branch",),
        "periodic_branch": ("periodic_branch",),
        "global_branch": ("global_branch",),
        "gate": ("gate",),
        "prediction_heads": ("local_head", "periodic_head", "global_head"),
    }
    named = dict(model.named_parameters())
    result: Dict[str, int] = {}
    for group, prefixes in groups.items():
        result[group] = sum(
            p.numel() for name, p in named.items()
            if p.requires_grad and any(name == prefix or name.startswith(prefix + ".") for prefix in prefixes)
        )
    result["total"] = sum(p.numel() for p in model.parameters() if p.requires_grad)
    return result


@torch.no_grad()
def run_model_sanity_check(model: SimpleGapAwareThreeBranchImputer, device: torch.device) -> None:
    model.eval()
    batch, length = 2, model.sequence_length
    x = torch.linspace(0.1, 3.0, length, device=device).repeat(batch, 1)
    mask = torch.ones_like(x)
    mask[:, 40:53] = 0.0
    output = model(x * mask, mask)
    expected = (batch, length)
    if output["prediction_norm"].shape != expected:
        raise RuntimeError("Sanity check failed: prediction shape")
    if output["branch_prediction_norm"].shape != (batch, length, 3):
        raise RuntimeError("Sanity check failed: branch prediction shape")
    for key in ("local_residual", "periodic_residual", "global_residual", "periodic_base"):
        if output[key].shape != expected:
            raise RuntimeError(f"Sanity check failed: {key} shape")
    if output["gate_weights"].shape != (batch, length, 3):
        raise RuntimeError("Sanity check failed: gate shape")
    if not torch.allclose(output["gate_weights"].sum(-1), torch.ones_like(x), atol=1e-5):
        raise RuntimeError("Sanity check failed: gates do not sum to one")
    branches = output["branch_prediction_norm"]
    if torch.allclose(branches[..., 0], branches[..., 1]) or torch.allclose(branches[..., 1], branches[..., 2]):
        raise RuntimeError("Sanity check failed: branch predictions are duplicated")
    if output["gap_features"].shape != (batch, length, 4):
        raise RuntimeError("Sanity check failed: gap features")
    dirty = x * mask + (1.0 - mask) * 9999.0
    dirty_output = model(dirty, mask)
    if not torch.allclose(output["periodic_base"], dirty_output["periodic_base"], atol=1e-5):
        raise RuntimeError("Sanity check failed: periodic base uses missing target values")
    for key in ("prediction_norm", "branch_prediction_norm", "gate_weights", "periodic_base"):
        if not torch.isfinite(output[key]).all():
            raise RuntimeError(f"Sanity check failed: non-finite {key}")
    all_missing = torch.zeros_like(mask)
    extreme = model(torch.zeros_like(x), all_missing)
    if not torch.isfinite(extreme["prediction_norm"]).all():
        raise RuntimeError("Sanity check failed: all-missing input is unsafe")
    pred = torch.tensor([[0.0, 3.0]], device=device)
    target = torch.zeros_like(pred)
    missing_mask = torch.zeros_like(pred)
    if torch.allclose(
        missing_huber_loss(pred, target, missing_mask, 0.2),
        missing_huber_loss(pred, target, missing_mask, 1.0),
    ):
        raise RuntimeError("Sanity check failed: Huber beta has no effect")
    count = sum(p.numel() for p in model.parameters() if p.requires_grad)
    if count > 500_000:
        raise RuntimeError(f"Parameter limit exceeded: {count} > 500000")
    model.train()


def compute_training_loss(
    output: Mapping[str, torch.Tensor],
    y: torch.Tensor,
    mask: torch.Tensor,
    beta: float,
    lambda_branch: float,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    y_norm = (y - output["mean"]) / output["std"]
    main_loss = missing_huber_loss(
        output["prediction_norm"], y_norm, mask, beta
    )
    if lambda_branch > 0:
        branch_losses = [
            missing_huber_loss(
                output["branch_prediction_norm"][..., i], y_norm, mask, beta
            )
            for i in range(3)
        ]
        branch_loss = torch.stack(branch_losses).mean()
    else:
        branch_loss = main_loss.detach() * 0.0
    total = main_loss + lambda_branch * branch_loss
    return total, main_loss, branch_loss


class MetricAccumulator:
    def __init__(self, patterns: Sequence[PatternSpec]) -> None:
        self.patterns = tuple(patterns)
        self.overall = self._empty_stats()
        self.by_pattern = {p.pattern_id: self._empty_stats() for p in patterns}
        type_names = sorted({p.missing_type for p in patterns})
        self.by_type = {name: self._empty_stats() for name in type_names}
        self.gate_by_pattern = {
            p.pattern_id: {"sum": np.zeros(3, dtype=np.float64), "count": 0}
            for p in patterns
        }
        self.loss_sum = 0.0
        self.loss_weight = 0

    @staticmethod
    def _empty_stats() -> Dict[str, float]:
        return {
            "abs": 0.0, "sq": 0.0, "smape": 0.0, "count": 0.0,
            "pcc_sum": 0.0, "pcc_count": 0.0,
        }

    @staticmethod
    def _safe_pcc(pred: torch.Tensor, true: torch.Tensor, eps: float = 1e-8):
        """Sample-wise PCC on missing positions; undefined samples are excluded."""
        if pred.numel() < 2:
            return None
        pred_centered = pred - pred.mean()
        true_centered = true - true.mean()
        pred_energy = torch.sum(pred_centered ** 2)
        true_energy = torch.sum(true_centered ** 2)
        denom = torch.sqrt(pred_energy * true_energy)
        if not torch.isfinite(denom) or float(denom.item()) <= eps:
            return None
        value = torch.sum(pred_centered * true_centered) / denom
        if not torch.isfinite(value):
            return None
        return float(value.clamp(-1.0, 1.0).item())

    @classmethod
    def _add_pcc(cls, stats: Dict[str, float], pred: torch.Tensor, true: torch.Tensor) -> None:
        value = cls._safe_pcc(pred, true)
        if value is not None:
            stats["pcc_sum"] += value
            stats["pcc_count"] += 1.0

    @staticmethod
    def _add(stats: Dict[str, float], pred: torch.Tensor, true: torch.Tensor) -> None:
        if pred.numel() == 0:
            return
        error = pred - true
        stats["abs"] += float(error.abs().sum().item())
        stats["sq"] += float((error**2).sum().item())
        smape = 200.0 * error.abs() / (pred.abs() + true.abs() + 1e-6)
        stats["smape"] += float(smape.sum().item())
        stats["count"] += float(pred.numel())

    def update(
        self,
        pred: torch.Tensor,
        true: torch.Tensor,
        mask: torch.Tensor,
        pattern_indices: torch.Tensor,
        gate_weights: torch.Tensor,
        loss: float,
    ) -> None:
        missing = mask < 0.5
        self._add(self.overall, pred[missing], true[missing])
        self.loss_sum += float(loss) * pred.shape[0]
        self.loss_weight += int(pred.shape[0])

        # PCC is intentionally sample-wise and macro-averaged. It is not
        # weighted by the number of missing points in a sample.
        for sample_index in range(pred.shape[0]):
            sample_missing = missing[sample_index]
            sample_pred = pred[sample_index][sample_missing]
            sample_true = true[sample_index][sample_missing]
            pattern = self.patterns[int(pattern_indices[sample_index].item())]
            self._add_pcc(self.overall, sample_pred, sample_true)
            self._add_pcc(self.by_pattern[pattern.pattern_id], sample_pred, sample_true)
            self._add_pcc(self.by_type[pattern.missing_type], sample_pred, sample_true)

        for pattern_index, pattern in enumerate(self.patterns):
            sample_selection = pattern_indices == pattern_index
            if not torch.any(sample_selection):
                continue
            local_missing = missing[sample_selection]
            local_pred = pred[sample_selection][local_missing]
            local_true = true[sample_selection][local_missing]
            self._add(self.by_pattern[pattern.pattern_id], local_pred, local_true)
            self._add(self.by_type[pattern.missing_type], local_pred, local_true)

            selected_gate = gate_weights[sample_selection][local_missing]
            if selected_gate.numel() > 0:
                self.gate_by_pattern[pattern.pattern_id]["sum"] += (
                    selected_gate.sum(dim=0).detach().cpu().numpy()
                )
                self.gate_by_pattern[pattern.pattern_id]["count"] += int(
                    selected_gate.shape[0]
                )

    @staticmethod
    def _finalize(stats: Mapping[str, float]) -> Dict[str, float]:
        count = max(float(stats["count"]), 1.0)
        pcc_count = int(stats["pcc_count"])
        return {
            "MAE": float(stats["abs"] / count),
            "RMSE": float(math.sqrt(stats["sq"] / count)),
            "SMAPE": float(stats["smape"] / count),
            "PCC": float(stats["pcc_sum"] / pcc_count) if pcc_count else float("nan"),
            "missing_points": int(stats["count"]),
            "valid_pcc_samples": pcc_count,
        }

    def finalize(self) -> Tuple[Dict[str, float], pd.DataFrame, pd.DataFrame, pd.DataFrame]:
        overall = self._finalize(self.overall)
        overall["loss"] = self.loss_sum / max(self.loss_weight, 1)

        pattern_rows = []
        for pattern in self.patterns:
            row = {
                "pattern_id": pattern.pattern_id,
                "missing_type": pattern.missing_type,
                "missing_level": pattern.missing_level,
            }
            row.update(self._finalize(self.by_pattern[pattern.pattern_id]))
            pattern_rows.append(row)

        type_rows = []
        for type_name, stats in self.by_type.items():
            row = {"missing_type": type_name}
            row.update(self._finalize(stats))
            type_rows.append(row)

        gate_rows = []
        for pattern in self.patterns:
            gate_stats = self.gate_by_pattern[pattern.pattern_id]
            count = max(int(gate_stats["count"]), 1)
            means = gate_stats["sum"] / count
            gate_rows.append(
                {
                    "pattern_id": pattern.pattern_id,
                    "local_weight": float(means[0]),
                    "period_weight": float(means[1]),
                    "global_weight": float(means[2]),
                    "missing_points": int(gate_stats["count"]),
                }
            )

        return (
            overall,
            pd.DataFrame(pattern_rows),
            pd.DataFrame(type_rows),
            pd.DataFrame(gate_rows),
        )


# -----------------------------------------------------------------------------
# Training and evaluation
# -----------------------------------------------------------------------------
def create_grad_scaler(enabled: bool):
    # torch.cuda.amp is used for compatibility with older PyTorch releases.
    return torch.cuda.amp.GradScaler(enabled=enabled)


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    scaler,
    device: torch.device,
    cfg: TrainConfig,
    epoch: int,
) -> Dict[str, float]:
    model.train()
    total_sum = 0.0
    main_sum = 0.0
    branch_sum = 0.0
    sample_count = 0
    amp_enabled = bool(cfg.amp and device.type == "cuda")

    progress = tqdm(loader, desc=f"Epoch {epoch:03d} train", leave=False)
    for batch in progress:
        x = batch["x"].to(device, non_blocking=True).float()
        mask = batch["mask"].to(device, non_blocking=True).float()
        y = batch["y"].to(device, non_blocking=True).float()

        optimizer.zero_grad(set_to_none=True)
        with torch.cuda.amp.autocast(enabled=amp_enabled):
            output = model(x, mask)
            total_loss, main_loss, branch_loss = compute_training_loss(
                output,
                y,
                mask,
                cfg.huber_beta,
                cfg.lambda_branch,
            )

        scaler.scale(total_loss).backward()
        scaler.unscale_(optimizer)
        if cfg.grad_clip > 0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
        scaler.step(optimizer)
        scaler.update()

        batch_size = x.shape[0]
        sample_count += batch_size
        total_sum += float(total_loss.detach().item()) * batch_size
        main_sum += float(main_loss.detach().item()) * batch_size
        branch_sum += float(branch_loss.detach().item()) * batch_size
        progress.set_postfix(loss=f"{total_sum / sample_count:.5f}")

    return {
        "train_total_loss": total_sum / max(sample_count, 1),
        "train_main_loss": main_sum / max(sample_count, 1),
        "train_branch_loss": branch_sum / max(sample_count, 1),
    }


@torch.no_grad()
def evaluate(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    cfg: TrainConfig,
    patterns: Sequence[PatternSpec],
    description: str,
    collect_examples: int = 0,
) -> Tuple[
    Dict[str, float], pd.DataFrame, pd.DataFrame, pd.DataFrame, List[Dict[str, object]]
]:
    model.eval()
    accumulator = MetricAccumulator(patterns)
    amp_enabled = bool(cfg.amp and device.type == "cuda")
    examples: List[Dict[str, object]] = []

    progress = tqdm(loader, desc=description, leave=False)
    for batch in progress:
        x = batch["x"].to(device, non_blocking=True).float()
        mask = batch["mask"].to(device, non_blocking=True).float()
        y = batch["y"].to(device, non_blocking=True).float()
        pattern_indices = batch["pattern_index"].to(device, non_blocking=True).long()

        with torch.cuda.amp.autocast(enabled=amp_enabled):
            output = model(x, mask)
            total_loss, _, _ = compute_training_loss(
                output,
                y,
                mask,
                cfg.huber_beta,
                cfg.lambda_branch,
            )

        prediction = output["prediction_norm"] * output["std"] + output["mean"]
        if cfg.nonnegative_clip:
            prediction = prediction.clamp_min(0.0)
        repaired = torch.where(mask > 0.5, x, prediction)

        accumulator.update(
            repaired,
            y,
            mask,
            pattern_indices,
            output["gate_weights"],
            float(total_loss.item()),
        )

        if collect_examples > 0 and len(examples) < collect_examples:
            remaining = collect_examples - len(examples)
            take = min(remaining, x.shape[0])
            x_cpu = x[:take].cpu().numpy()
            mask_cpu = mask[:take].cpu().numpy()
            y_cpu = y[:take].cpu().numpy()
            repaired_cpu = repaired[:take].cpu().numpy()
            pattern_cpu = pattern_indices[:take].cpu().numpy()
            for index in range(take):
                missing_indices = np.flatnonzero(mask_cpu[index] < 0.5)
                examples.append(
                    {
                        "sample_id": str(batch["sample_id"][index]),
                        "clean_id": str(batch["clean_id"][index]),
                        "meter_id": str(batch["meter_id"][index]),
                        "pattern_id": patterns[int(pattern_cpu[index])].pattern_id,
                        "missing_indices": json.dumps(missing_indices.tolist()),
                        "true_missing": json.dumps(
                            y_cpu[index, missing_indices].round(6).tolist()
                        ),
                        "pred_missing": json.dumps(
                            repaired_cpu[index, missing_indices].round(6).tolist()
                        ),
                    }
                )

    overall, by_pattern, by_type, gate = accumulator.finalize()
    return overall, by_pattern, by_type, gate, examples


def make_loader(
    dataset: Dataset,
    batch_size: int,
    shuffle: bool,
    num_workers: int,
    seed: int,
    device: torch.device,
) -> DataLoader:
    generator = torch.Generator()
    generator.manual_seed(seed)
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=(device.type == "cuda"),
        drop_last=False,
        worker_init_fn=seed_worker,
        generator=generator,
        persistent_workers=False,
    )


def save_json(path: Path, payload: Mapping[str, object]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)


def save_evaluation(
    out_dir: Path,
    prefix: str,
    overall: Mapping[str, float],
    by_pattern: pd.DataFrame,
    by_type: pd.DataFrame,
    gate: pd.DataFrame,
    examples: Sequence[Mapping[str, object]],
) -> None:
    save_json(out_dir / f"{prefix}_metrics.json", dict(overall))
    by_pattern.to_csv(out_dir / f"{prefix}_metrics_by_pattern.csv", index=False)
    by_type.to_csv(out_dir / f"{prefix}_metrics_by_type.csv", index=False)
    gate.to_csv(out_dir / f"{prefix}_gate_statistics.csv", index=False)
    if examples:
        pd.DataFrame(examples).to_csv(
            out_dir / f"{prefix}_prediction_examples.csv", index=False
        )


def plot_history(history: pd.DataFrame, out_path: Path) -> None:
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        return
    figure = plt.figure(figsize=(8, 5))
    axis = figure.add_subplot(111)
    axis.plot(history["epoch"], history["val_MAE"], label="Val MAE")
    axis.plot(history["epoch"], history["val_RMSE"], label="Val RMSE")
    axis.set_xlabel("Epoch")
    axis.set_ylabel("Error")
    axis.grid(True, alpha=0.3)
    axis.legend()
    figure.tight_layout()
    figure.savefig(out_path, dpi=160)
    plt.close(figure)


def main() -> None:
    cfg = parse_args()
    if cfg.ablation == "no_auxiliary_loss":
        cfg.lambda_branch = 0.0
    seed_everything(cfg.seed)

    data_dir = Path(cfg.data_dir)
    out_dir = Path(cfg.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    train_path = data_dir / "train.csv"
    val_path = data_dir / "val.csv"
    test_path = data_dir / "test.csv"
    required_paths = (train_path, val_path) if cfg.skip_test else (train_path, val_path, test_path)
    for path in required_paths:
        if not path.exists():
            raise FileNotFoundError(path)

    patterns, mixed_random_ratio = load_patterns(data_dir)
    pattern_to_index, pattern_index_to_name = make_pattern_maps(patterns)
    # During hyperparameter search, --skip_test enforces a strict validation-only
    # protocol: test.csv is neither loaded nor audited.
    data_audit = audit_datasets(
        train_path, val_path, None if cfg.skip_test else test_path, patterns
    )
    save_json(
        out_dir / "run_config.json",
        {
            "training": asdict(cfg),
            "patterns": [asdict(p) for p in patterns],
            "mixed_random_ratio": mixed_random_ratio,
            "data_audit": data_audit,
        },
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    amp_enabled = bool(cfg.amp and device.type == "cuda")
    if device.type == "cuda":
        torch.cuda.reset_peak_memory_stats(device)
    print("=" * 80)
    print("CER gap-aware three-branch imputer training")
    print("=" * 80)
    print(f"Device: {device}")
    if device.type == "cuda":
        print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"AMP: {amp_enabled}")
    print(f"Data directory: {data_dir.resolve()}")
    print(f"Output directory: {out_dir.resolve()}")
    print(f"Online patterns: {', '.join(p.pattern_id for p in patterns)}")
    print("Training pattern coverage: ALL 9 patterns per clean window per epoch")

    print("\nLoading train.csv ...")
    train_dataset = OnlineMaskTrainDataset(
        train_path,
        patterns,
        mixed_random_ratio,
        cfg.seed,
    )
    print("Loading val.csv ...")
    val_dataset = FixedMaskDataset(val_path, pattern_to_index)
    test_protocol_dataset = None
    if not cfg.skip_test:
        print("Loading test.csv for fixed-mask protocol check ...")
        test_protocol_dataset = FixedMaskDataset(test_path, pattern_to_index)
    check_mask_protocols(train_dataset, val_dataset, test_protocol_dataset)
    del test_protocol_dataset
    gc.collect()
    if train_dataset.sequence_length != val_dataset.x.shape[1]:
        raise RuntimeError("Train and validation sequence lengths differ")
    sequence_length = train_dataset.sequence_length
    print(f"Train clean windows: {train_dataset.num_clean_windows:,}")
    print(f"Effective training samples/epoch: {len(train_dataset):,}")
    print(f"Validation fixed-mask samples: {len(val_dataset):,}")
    print(f"Sequence length: {sequence_length}")

    train_loader = make_loader(
        train_dataset,
        cfg.batch_size,
        True,
        cfg.num_workers,
        cfg.seed + 10,
        device,
    )
    val_loader = make_loader(
        val_dataset,
        cfg.batch_size,
        False,
        cfg.num_workers,
        cfg.seed + 20,
        device,
    )

    model = SimpleGapAwareThreeBranchImputer(
        sequence_length=sequence_length,
        local_dim=cfg.local_dim,
        periodic_dim=cfg.periodic_dim,
        global_dim=cfg.global_dim,
        local_blocks=cfg.local_blocks,
        periodic_heads=cfg.periodic_heads,
        gate_hidden_dim=cfg.gate_hidden_dim,
        gate_input=cfg.gate_input,
        dropout=cfg.dropout,
        ablation=cfg.ablation,
    ).to(device)
    parameter_count = sum(p.numel() for p in model.parameters() if p.requires_grad)
    if parameter_count > 500_000:
        raise RuntimeError(f"Parameter limit exceeded: {parameter_count} > 500000")
    run_model_sanity_check(model, device)
    breakdown = parameter_breakdown(model)
    save_json(
        out_dir / "run_config.json",
        {
            "model_name": MODEL_NAME,
            "training": asdict(cfg),
            "model": {
                "local_dim": model.local_dim,
                "periodic_dim": model.periodic_dim,
                "global_dim": model.global_dim,
                "local_blocks": model.local_blocks,
                "periodic_heads": model.periodic_heads,
                "gate_hidden_dim": model.gate_hidden_dim,
                "gate_input": model.gate_input,
                "ablation": model.ablation,
                "dropout": cfg.dropout,
                "parameter_count": parameter_count,
                "parameter_breakdown": breakdown,
            },
            "patterns": [asdict(p) for p in patterns],
            "mixed_random_ratio": mixed_random_ratio,
            "data_audit": data_audit,
            "selection_policy": "Validation MAE selects the checkpoint; test is evaluated only after loading that checkpoint.",
        },
    )
    print("Model sanity check: PASS")
    print(f"Model: {MODEL_NAME}; gate_input: {cfg.gate_input}; ablation: {cfg.ablation}")
    print(f"Trainable parameters: {parameter_count:,}")

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=cfg.learning_rate,
        weight_decay=cfg.weight_decay,
    )
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=cfg.scheduler_factor,
        patience=cfg.scheduler_patience,
    )
    scaler = create_grad_scaler(amp_enabled)

    best_mae = float("inf")
    best_epoch = 0
    epochs_without_improvement = 0
    history_rows: List[Dict[str, float]] = []
    checkpoint_path = out_dir / "best_model.pt"
    start_time = time.time()

    for epoch in range(1, cfg.epochs + 1):
        train_dataset.set_epoch(epoch)
        epoch_start = time.time()
        train_result = train_one_epoch(
            model,
            train_loader,
            optimizer,
            scaler,
            device,
            cfg,
            epoch,
        )
        val_overall, _, _, _, _ = evaluate(
            model,
            val_loader,
            device,
            cfg,
            patterns,
            description=f"Epoch {epoch:03d} val",
        )
        scheduler.step(val_overall["MAE"])
        current_lr = float(optimizer.param_groups[0]["lr"])
        epoch_seconds = time.time() - epoch_start

        row = {
            "epoch": epoch,
            **train_result,
            "val_loss": val_overall["loss"],
            "val_MAE": val_overall["MAE"],
            "val_RMSE": val_overall["RMSE"],
            "val_SMAPE": val_overall["SMAPE"],
            "val_PCC": val_overall["PCC"],
            "learning_rate": current_lr,
            "epoch_seconds": epoch_seconds,
        }
        history_rows.append(row)
        history_frame = pd.DataFrame(history_rows)
        history_frame.to_csv(out_dir / "training_history.csv", index=False)

        improved = val_overall["MAE"] < best_mae - cfg.min_delta
        if improved:
            best_mae = float(val_overall["MAE"])
            best_epoch = epoch
            epochs_without_improvement = 0
            torch.save(
                {
                    "epoch": epoch,
                    "best_val_mae": best_mae,
                    "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "config": asdict(cfg),
                    "patterns": [asdict(p) for p in patterns],
                    "sequence_length": sequence_length,
                    "parameter_count": parameter_count,
                    "parameter_breakdown": breakdown,
                    "model_name": MODEL_NAME,
                },
                checkpoint_path,
            )
        else:
            epochs_without_improvement += 1

        marker = " *" if improved else ""
        print(
            f"Epoch {epoch:03d} | train={train_result['train_total_loss']:.6f} "
            f"| val MAE={val_overall['MAE']:.6f} "
            f"RMSE={val_overall['RMSE']:.6f} "
            f"SMAPE={val_overall['SMAPE']:.3f}% "
            f"PCC={val_overall['PCC']:.6f} "
            f"| lr={current_lr:.2e} | {epoch_seconds:.1f}s{marker}"
        )

        if epochs_without_improvement >= cfg.patience:
            print(
                f"Early stopping: no validation MAE improvement for {cfg.patience} epochs."
            )
            break

    total_training_seconds = time.time() - start_time
    history_frame = pd.DataFrame(history_rows)
    plot_history(history_frame, out_dir / "training_history.png")

    if not checkpoint_path.exists():
        raise RuntimeError("No best checkpoint was saved")
    checkpoint = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(checkpoint["model_state_dict"])
    print("\n" + "=" * 80)
    print(f"Best epoch: {best_epoch}")
    print(f"Best validation MAE: {best_mae:.6f}")
    print(f"Training time: {total_training_seconds:.1f} seconds")

    val_overall, val_by_pattern, val_by_type, val_gate, val_examples = evaluate(
        model,
        val_loader,
        device,
        cfg,
        patterns,
        description="Final validation",
        collect_examples=min(cfg.save_prediction_examples, 20),
    )
    save_evaluation(
        out_dir,
        "validation",
        val_overall,
        val_by_pattern,
        val_by_type,
        val_gate,
        val_examples,
    )
    print(
        f"Final validation | MAE={val_overall['MAE']:.6f} "
        f"RMSE={val_overall['RMSE']:.6f} SMAPE={val_overall['SMAPE']:.3f}% "
        f"PCC={val_overall['PCC']:.6f}"
    )
    print("\nValidation by pattern:")
    print(val_by_pattern[["pattern_id", "MAE", "RMSE", "SMAPE", "PCC"]].to_string(index=False))

    # Free validation arrays before loading the test CSV to reduce peak memory.
    del val_loader, val_dataset
    gc.collect()

    test_overall: Optional[Dict[str, float]] = None
    test_inference_seconds: Optional[float] = None
    if not cfg.skip_test:
        print("\nLoading test.csv for one-time final evaluation ...")
        test_dataset = FixedMaskDataset(test_path, pattern_to_index)
        test_loader = make_loader(
            test_dataset,
            cfg.batch_size,
            False,
            cfg.num_workers,
            cfg.seed + 30,
            device,
        )
        if device.type == "cuda":
            torch.cuda.synchronize(device)
        inference_start = time.time()
        test_overall, test_by_pattern, test_by_type, test_gate, test_examples = evaluate(
            model,
            test_loader,
            device,
            cfg,
            patterns,
            description="Final test",
            collect_examples=cfg.save_prediction_examples,
        )
        if device.type == "cuda":
            torch.cuda.synchronize(device)
        test_inference_seconds = time.time() - inference_start
        save_evaluation(
            out_dir,
            "test",
            test_overall,
            test_by_pattern,
            test_by_type,
            test_gate,
            test_examples,
        )
        print(
            f"Final test | MAE={test_overall['MAE']:.6f} "
            f"RMSE={test_overall['RMSE']:.6f} SMAPE={test_overall['SMAPE']:.3f}% "
            f"PCC={test_overall['PCC']:.6f}"
        )
        print("\nTest by pattern:")
        print(test_by_pattern[["pattern_id", "MAE", "RMSE", "SMAPE", "PCC"]].to_string(index=False))

    max_gpu_memory_mb = (torch.cuda.max_memory_allocated(device) / (1024 ** 2) if device.type == "cuda" else 0.0)
    final_summary: Dict[str, object] = {
        "model_name": MODEL_NAME,
        "loss_name": "Smooth L1 (Huber) Loss",
        "script": Path(__file__).name,
        "huber_beta": cfg.huber_beta,
        "lambda_branch": cfg.lambda_branch,
        "local_dim": model.local_dim,
        "periodic_dim": model.periodic_dim,
        "global_dim": model.global_dim,
        "local_blocks": model.local_blocks,
        "periodic_heads": model.periodic_heads,
        "gate_hidden_dim": model.gate_hidden_dim,
        "gate_input": model.gate_input,
        "ablation": model.ablation,
        "best_epoch": best_epoch,
        "best_validation_mae": best_mae,
        "best_validation_mae_during_training": best_mae,
        "parameter_count": parameter_count,
        "parameter_breakdown": breakdown,
        "training_seconds": total_training_seconds,
        "average_epoch_seconds": total_training_seconds / max(len(history_rows), 1),
        "test_inference_seconds": test_inference_seconds,
        "max_gpu_memory_mb": max_gpu_memory_mb,
        "validation": val_overall,
        "test": test_overall,
        "checkpoint": str(checkpoint_path.resolve()),
        "run_config_path": str((out_dir / "run_config.json").resolve()),
    }
    save_json(out_dir / "final_summary.json", final_summary)

    print("\nGenerated files:")
    for path in sorted(out_dir.iterdir()):
        print(f"  {path.name}")


if __name__ == "__main__":
    main()
